- name: Stop k3s-init
  systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Stop k3s
  systemd:
    name: k3s
    state: stopped
  failed_when: false

- name: Initialize cluster
  command:
    cmd: "systemd-run --unit=k3s-init k3s server --cluster-init --token ${k3s_token}"