- name: Stop k3s-init
  systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Stop k3s
  systemd:
    name: k3s
    state: stopped
  failed_when: false

- name: Deploy virtual ip manifest
  include_tasks: virtual_ip.yaml