- name: Stop k3s-init
  systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Stop k3s
  systemd:
    name: k3s
    state: stopped
  failed_when: false

- name: Initialize cluster
  command:
    cmd: "systemd-run -p RestartSec=2 -p Restart=on-failure --unit=k3s-init k3s server --cluster-init --token {{k3s_token}}"
    creates: "{{systemd_directory}}/k3s-init.service"

- name: Validate
  when: not ansible_check_mode
  block:
    - name: Validate
      command:
        cmd: k3s kubectl get nodes -l "node-role.kubernetes.io/master=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups[control_plane_group | default('control_plane')] | length)
      retries: 20
      delay: 10
      changed_when: false
  always:
    - name: Kill initialization service
      systemd:
        name: k3s-init
        state: stopped
      failed_when: false