- name: install k3s
  hosts: kube_cluster
  gather_facts: true
  roles:
    - role: prerequisites
      become: true
    - role: download
      become: true

- name: Setup k3s control plane
  hosts: control_plane
  roles:
    - role: k3s_control_plane
      become: true