- name: Make directory - manifests
  file:
    path: /tmp/k3s
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ groups[control_plane_group | default('k3s-control-0')] }}"
  run_once: true