- name: Copy k3s.service.j2 file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "{{systemd_directory}}/k3s-node.service"
    owner: root
    group: root
    mode: '0755'

- name: Restart k3s service
  ansible.builtin.systemd:
    name: k3s-node
    daemon_reload: true
    state: restarted
    enabled: true